[package]
name = "dictcc_trans"
version = "0.1.0"
authors = ["Max Hausch <cheriimoya@googlemail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.8", features = ["blocking"] }
scraper = "0.12.0"
select = "0.5.0"
pico-args = "0.3.4"
